export const criarGrupoPago = `
    INSERT INTO groups (
        id, 
        name, 
        description, 
        group_type, 
        price, 
        currency, 
        creator_id, 
        created_at, 
        member_limit, 
        cover_image, 
        access_type, 
        selected_provider_id, 
        expiration_date, 
        vip_door, 
        pixel_id, 
        pixel_token,
        is_vip,
        status
    ) 
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
    RETURNING 
        id,
        name,
        description,
        group_type,
        price,
        currency,
        creator_id,
        created_at,
        member_limit,
        cover_image,
        access_type,
        selected_provider_id,
        expiration_date,
        vip_door,
        pixel_id,
        pixel_token;
`;
